# -*- coding: utf-8 -*-
"""Binarize_粒子解析.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bCODwzbgTCiW5NiKrqKhuMQWQZpvwWr
"""

from PIL import Image
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 画像ファイルのパスを指定してください
image_path = 'testA1.tiff'
img = Image.open(image_path).convert("L")
img = np.array(img).astype(np.uint8)
# --- 通常の二値化 ---
_, mask = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
plt.gray()
plt.imshow(mask)
plt.axis("off")

from skimage.measure import label, regionprops

label_img = label(mask)

# --- 粒子解析 ---
props = regionprops(label_img)
areas = [p.area for p in props]
diameters = [2 * np.sqrt(p.area / np.pi) for p in props]

# --- 結果の集計例 ---
print(f"粒子数: {len(props)}")
print(f"平均面積: {np.mean(areas):.1f} px²")
print(f"平均円相当径: {np.mean(diameters):.1f} px")

# --- 結果の描画 ---
fig, ax = plt.subplots(figsize=(4, 4))
ax.imshow(mask, cmap='gray')
for p in props:
    y, x = p.centroid
    ax.text(x, y, f"{int(2*np.sqrt(p.area/np.pi))}", color='red', fontsize=8, ha='center')
ax.axis('off')
plt.show()

# ① ヒストグラム ------------------------------------------------
plt.figure(figsize=(5,3))
plt.hist(diameters, bins=8, color='skyblue', edgecolor='black')
plt.xlabel("Equivalent Diameter [px]", fontsize=11)
plt.ylabel("Count", fontsize=11)
#plt.title("粒径分布ヒストグラム", fontsize=13)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# ② 箱ひげ図 ------------------------------------------------
plt.figure(figsize=(3,4))
plt.boxplot(diameters, patch_artist=True,
            boxprops=dict(facecolor='lightgreen', color='black'),
            medianprops=dict(color='red', linewidth=2))
plt.ylabel("Equivalent Diameter [px]", fontsize=11)
#plt.title("円相当径の箱ひげ図", fontsize=13)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# ③ 散布図 ------------------------------------------------
plt.figure(figsize=(5,3))
plt.scatter(areas, diameters, color='orange', edgecolors='black', s=50)
plt.xlabel("Area [px²]", fontsize=11)
plt.ylabel("Equivalent Diameter [px]", fontsize=11)
#plt.title("面積と円相当径の関係（散布図）", fontsize=13)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

