# -*- coding: utf-8 -*-
"""Binarize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bCODwzbgTCiW5NiKrqKhuMQWQZpvwWr
"""

from PIL import Image
import cv2
import numpy as np

# 画像ファイルのパスを指定してください
image_path = 'testB1.png'
img = Image.open(image_path).convert("L")
img = np.array(img).astype(np.uint8)
# --- 通常の二値化 ---
_, binary_fixed = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

binary_fixed

# 画像ファイルのパスを指定してください
image_path = 'testB1.png'
img = Image.open(image_path).convert("L")
img = np.array(img).astype(np.uint8)
# --- 通常の二値化 ---
thresh_val, binary_otsu = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

binary_otsu

