# -*- coding: utf-8 -*-
"""Filter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bCODwzbgTCiW5NiKrqKhuMQWQZpvwWr
"""

from PIL import Image
import cv2
import numpy as np

# 画像ファイルのパスを指定してください
image_path = 'testB1.png'
img = Image.open(image_path)
img = np.array(img)
filtered = cv2.medianBlur(img, 9)
filtered

