# -*- coding: utf-8 -*-
"""Histogram Equalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bCODwzbgTCiW5NiKrqKhuMQWQZpvwWr
"""

from PIL import Image
import cv2
import numpy as np

# 画像ファイルのパスを指定してください
image_path = 'testB1.png'
img = Image.open(image_path).convert("L")
img = np.array(img).astype(np.uint8)
equalized = cv2.equalizeHist(img)
equalized

