# -*- coding: utf-8 -*-
"""Read_image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bCODwzbgTCiW5NiKrqKhuMQWQZpvwWr
"""

from PIL import Image

# 画像ファイルのパスを指定してください
image_path = 'testB1.png'
img = Image.open(image_path)

img

